-- 002: DB schema bootstrap for MVP

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  display_name text not null,
  avatar_url text,
  bio text,
  is_admin boolean not null default false,
  is_poster boolean not null default false,
  is_suspended boolean not null default false,
  created_at timestamptz not null default now(),
  constraint profiles_username_length_check check (
    username is null or char_length(username) between 3 and 30
  )
);

create unique index if not exists profiles_username_unique_idx
  on public.profiles (lower(username))
  where username is not null;

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  caption text,
  category text,
  taken_at date,
  image_path text not null,
  mime_type text,
  file_size bigint,
  width integer,
  height integer,
  visibility text not null default 'public',
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint posts_visibility_check check (visibility in ('public', 'private')),
  constraint posts_file_size_check check (file_size is null or file_size > 0),
  constraint posts_width_check check (width is null or width > 0),
  constraint posts_height_check check (height is null or height > 0)
);

create index if not exists posts_feed_idx
  on public.posts (user_id, created_at desc)
  where deleted_at is null;

create index if not exists posts_visibility_created_at_idx
  on public.posts (visibility, created_at desc)
  where deleted_at is null;

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists tags_name_unique_idx
  on public.tags (lower(name));

create table if not exists public.post_tags (
  post_id uuid not null references public.posts(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, tag_id)
);

create index if not exists post_tags_tag_id_idx
  on public.post_tags (tag_id);

create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followee_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followee_id),
  constraint follows_not_self_check check (follower_id <> followee_id)
);

create index if not exists follows_followee_id_idx
  on public.follows (followee_id);

create table if not exists public.likes (
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index if not exists likes_user_id_idx
  on public.likes (user_id);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint comments_body_not_blank_check check (char_length(trim(body)) > 0)
);

create index if not exists comments_post_id_created_at_idx
  on public.comments (post_id, created_at asc)
  where deleted_at is null;

create index if not exists comments_user_id_idx
  on public.comments (user_id);
